### ISSUE TITLE
Snap builds broken on master

### ISSUE THREAD

**Issue by maxiberta** [moonlight-stream/moonlight-qt#380]
Hi! [Snap builds are currently broken](https://code.launchpad.net/~maxiberta/+snap/moonlight-edge) on master:
```
gui/sdlgamepadkeynavigation.cpp: In member function ‘void SdlGamepadKeyNavigation::sendWheel(QPoint&)’:
gui/sdlgamepadkeynavigation.cpp:253:145: error: no matching function for call to ‘QWheelEvent::QWheelEvent(QPoint&, QPoint&, QPoint, QPoint&, int, int, Qt::ScrollPhase, bool, Qt::MouseEventSource)’
         QWheelEvent wheelEvent(mousePos, globalPos, QPoint(), angleDelta, 0, 0, Qt::NoScrollPhase, false, Qt::MouseEventSynthesizedByApplication);
```
I think [this is the relevant commit](https://github.com/moonlight-stream/moonlight-qt/commit/fbaa70a2ae37fc82f7af5df10d66cf2a1134a188#diff-75a010830606d539a534e616b5cc5a90R253).  I'm no expert but it looks like a newer Qt is expected? 

The snap is currently based on `core18 + Qt 5.9`. It could hopefully be based on `core20 + Qt 5.12` soon, but [the `qmake` plugin does not yet support `core20`](https://github.com/snapcore/snapcraft/releases/tag/4.0). Alternatively, the snap could use a custom build of Qt - feasible, but not trivial.

Cheers! o/

**Comment by cgutman** [comment]
Thanks, I pushed a fix. I saw that the Steam Link's Qt 5.9 build was failing too.

On the subject of a newer Qt, I am hoping to be able to drop Qt 5.9 support soon. It will also be nice to have the dependencies and other libraries updated too.

Maybe we could make it work with `core20` on Snapcraft 4.0 by using the `make` plugin and using `override-build` to run qmake first?

**Comment by maxiberta** [comment]
Quick update: already published a `core20` based snap to the `edge` channel (the `make` hack was a great idea, btw!).
Bad news: `core20` is amd64 only. But the i386 snap has ~100 active users and I'd rather not leave them unsupported. So, considering/trying alternatives:
- Go back to `core18` and use the kde-neon PPA.
- Go back to `core18` and depend on the KF5 content snap.

**Comment by maxiberta** [comment]
Update: the snap on `edge` is now based on `core18` + kde-neon (Qt 5.14.2) - both amd64 and i386.
